// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qarwfkkebnmxnwqkgdqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhcndma2tlYm5teG53cWtnZHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTI0OTUsImV4cCI6MjA2NjM2ODQ5NX0.ixjUAyL_z1H5M4uThmpZN7qzV5FmDc_uu0vzPjYx75A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});